# Generated by Django 4.0.4 on 2022-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='place_of_pub',
            field=models.ManyToManyField(help_text='Select a place for this book', to='stacks.place'),
        ),
    ]
