# Generated by Django 4.0.4 on 2022-06-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0002_alter_book_place_of_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Select a genre for this book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stacks.genre'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='place_of_pub',
        ),
        migrations.AddField(
            model_name='book',
            name='place_of_pub',
            field=models.ForeignKey(help_text='Select a place for this book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stacks.place'),
        ),
    ]
