# Generated by Django 4.0.4 on 2022-06-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0003_remove_book_genre_book_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year_of_pub',
            new_name='date_of_pub',
        ),
    ]
