# Generated by Django 4.0.4 on 2022-06-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0007_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view_personal_bookshelf', 'view personal bookshelf'),)},
        ),
    ]
