# Generated by Django 4.0.4 on 2022-07-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0008_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_pub',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
