# Generated by Django 4.0.4 on 2022-07-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0009_alter_book_date_of_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
