# Generated by Django 4.0.4 on 2022-07-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0010_book_page_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='place_of_pub',
        ),
    ]
