# Generated by Django 4.0.4 on 2022-07-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0011_remove_book_place_of_pub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view_personal_bookshelf', 'view personal bookshelf'), ('can_edit_personal_bookshelf', 'edit personal bookshelf'))},
        ),
    ]
