# Generated by Django 4.0.4 on 2022-07-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0012_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='country_of_pub',
            field=models.ManyToManyField(null=True, to='stacks.place'),
        ),
    ]
