# Generated by Django 4.0.4 on 2022-07-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0013_book_country_of_pub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='country_of_pub',
        ),
        migrations.AddField(
            model_name='book',
            name='country_of_pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stacks.place'),
        ),
    ]
